### PR TITLE
US59587

### PR DESCRIPTION
**Pull request by LavaFields**
Add optional support for label, listId and notation
Updated readme
Added linting analysis as a build step to catch js issues during build and provide static analysis in IDE
Fixed list item indentation when lines wraps
Updated versions of devDependencies
Rolled version to 1.0.0

### CODE REVIEW

**Comment by LavaFields** [comment]
I need to publish this lib before I can open up the other reviews for this story (authoring and mapping) because I will need to use the new version 1.0.0 of this lib, which hasn't been published yet.

**Comment by mdedys** [comment]
Changes look good to me. Approved!

**Comment by sebastianmihai** [comment]
Approved, but spend a bit of time seeing if it's easy to convert to jsx syntax from React.createElement.

**Comment by LavaFields** [comment]
Converted to JSX

**Pull request merged**
